// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef SPRITEPALETTE_PALETTE_INCLUDE_H
#define SPRITEPALETTE_PALETTE_INCLUDE_H

#include "palette_types.h"
#include "resource_types.h"

RESOURCE() extern const PaletteResource spritePalette;

#endif

