// File generated by SpriteMaster. https://github.com/pw32x/ninjagirl
#ifndef CAR001_ANIMATION_INCLUDE_H
#define CAR001_ANIMATION_INCLUDE_H

#include "animation_types.h"
#include "resource_types.h"

RESOURCE() extern const BatchedAnimation car001;

#define CAR001_NUMFRAMES 16

#endif

